services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env.local
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}
      - REACT_APP_URL=${REACT_APP_URL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${FRONTEND_PORT}"]
      interval: 30s
      timeout: 3s
      retries: 3