@echo off
echo Starting Medical AI Platform Local Test...

echo Starting Backend...
start cmd /k "cd backend && python main.py"

echo Waiting for backend to start...
timeout /t 20

echo Starting Frontend...
start cmd /k "cd my-app && npm start"

echo Waiting for frontend to start...
timeout /t 5

echo Opening test page...
start http://localhost:3000

echo Both services are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
echo Press any key to continue...
pause

REM ./start-local-test.bat