name: Deploy to Github Actions

on:
  push:
    branches: [ "cicd" ]

permissions:
  contents: read

jobs:

  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest
    environment: frontend
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_WS_URL: ${{ secrets.REACT_APP_WS_URL }}
      REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
      REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
      FRONTEND_HOST_PORT: ${{ secrets.FRONTEND_HOST_PORT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend with compose
      run: docker compose build

    - name: Start frontend service
      run: docker compose up -d

    - name: Wait for frontend to be ready
      run: sleep 10

    - name: Test frontend
      run: |
        docker compose logs frontend
        curl -f http://localhost:3000 || echo "Frontend not ready"

    - name: Cleanup
      run: docker compose down