name: Deploy to Github Actions

on:
  push:
    branches: [ "cicd" ]

permissions:
  contents: read

jobs:

  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest
    environment: frontend
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_WS_URL: ${{ secrets.REACT_APP_WS_URL }}
      REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
      REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
      FRONTEND_HOST_PORT: ${{ secrets.FRONTEND_HOST_PORT }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      API_PORT: ${{ secrets.API_PORT }}
      DOCKERHUB_FRONTEND: ${{ secrets.DOCKERHUB_FRONTEND }}
      DOCKERHUB_BACKEND: ${{ secrets.DOCKERHUB_BACKEND }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pull frontend image from Docker Hub
      run: docker pull ${{ secrets.DOCKERHUB_FRONTEND }}

    - name: Pull backend image from Docker Hub
      run: docker pull ${{ secrets.DOCKERHUB_BACKEND }}

    - name: Start services
      run: docker compose up -d

    - name: Wait for frontend to be ready
      run: sleep 10

    - name: Test frontend
      run: |
        docker compose logs frontend
        curl -f http://localhost:3000 || echo "Frontend not ready"

    - name: Cleanup
      run: docker compose down