name: Build and Push Frontend to DockerHub

on:
  push:
    branches: [ "cicd2" ]
    paths:
      - 'my-app/**'
      - 'Dockerfile.frontend'
      - '.github/workflows/frontend-dockerhub.yml'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/ai-healthcare-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          REACT_APP_API_URL=${{ secrets.ALB_URL }}/api
          REACT_APP_WS_URL=ws://${{ secrets.ALB_DNS_NAME }}/api
          REACT_APP_URL=${{ secrets.ALB_URL }}


    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}

    - name: Update deployment summary
      run: |
        echo "## 🚀 Frontend Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image:** \`${{ env.DOCKER_IMAGE }}:latest\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags:** ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "- **API URL:** \`${{ secrets.ALB_URL }}/api\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Built with ALB URLs:** ✅" >> $GITHUB_STEP_SUMMARY
        echo "- **Next:** Update ECS task definition to use new image" >> $GITHUB_STEP_SUMMARY